# Generated by Django 4.2.9 on 2025-06-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_save',
            field=models.BooleanField(default=True),
        ),
    ]
