# Generated by Django 4.2.6 on 2023-12-02 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationTask",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "source_language",
                    models.CharField(default="English", max_length=255),
                ),
                (
                    "target_language",
                    models.CharField(default="Persian", max_length=255),
                ),
                ("source_text", models.TextField()),
                ("queried_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
