# Generated by Django 4.2.6 on 2023-12-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="translationtask",
            old_name="queried_at",
            new_name="save_time",
        ),
        migrations.AddField(
            model_name="translationtask",
            name="translation",
            field=models.TextField(null=True),
        ),
    ]
