# Generated by Django 4.2.6 on 2024-09-10 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_rename_queried_at_translationtask_save_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTranslationTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_language', models.CharField(default='English', max_length=255)),
                ('target_language', models.CharField(default='Persian', max_length=255)),
                ('save_time', models.DateTimeField(auto_now_add=True)),
                ('translated_percentage', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
