# Generated by Django 4.2.6 on 2024-09-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_filetranslationtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetranslationtask',
            old_name='translated_percentage',
            new_name='progress',
        ),
    ]
