# Generated by Django 4.2.6 on 2024-09-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_translated_percentage_filetranslationtask_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetranslationtask',
            name='progress',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
