# Generated by Django 4.2.6 on 2025-03-12 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_filetranslationtask_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='speechTranslationTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_language', models.CharField(default='English', max_length=255)),
                ('target_language', models.CharField(default='Persian', max_length=255)),
                ('task_time', models.DateTimeField(auto_now_add=True)),
                ('progress', models.CharField(max_length=32, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
