# Generated by Django 4.2.6 on 2025-03-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_save_time_filetranslationtask_task_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='speechTranslationTask',
        ),
    ]
