# Generated by Django 4.2.6 on 2025-03-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_speechtranslationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetranslationtask',
            name='task_type',
            field=models.CharField(choices=[('speech', 'speech'), ('doc', 'doc')], default='doc', max_length=10),
        ),
    ]
